name: Conditional Job Workflow

on:
  push:
    branches:
      - main
    paths:
      - "sampleaction/**"
      - "test/**"
      - "./github/workflows/test3.yml"

jobs:
  check_folder_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check folder changes
        id: folder_changes
        # run: echo "::set-output name=changed::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})"
        run: echo "::set-output name=changed::$(git diff --name-only main ${GITHUB_SHA})"
  # conditional_job:
  #   needs: check_folder_changes
  #   runs-on: ubuntu-latest
  #   if: ${{ contains(needs.check_folder_changes.outputs.changed, 'sampleaction/') }}
  #   steps:
  #     - name: Run conditional job
  #       run: echo "This job runs only if 'test/' folder is changed"
  conditional_job:
    needs: check_folder_changes
    runs-on: ubuntu-latest
    if: ${{ contains(needs.check_folder_changes.outputs.changed, 'sampleaction/') }}
    steps:
      - name: Run conditional job
        run: echo "This job runs only if 'test/' folder is changed"
