name: sample
on:
  push:
    branches:
      - "main"

jobs:
  conditional_job_check_files:
    runs-on: "ubuntu-20.04"
    # Declare outputs for next jobs
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2
      - shell: bash
        id: check_file_changed
        run: |
          diff=$(git diff --name-only HEAD^ HEAD) 
          sourceDiff=false
          echo "working"
          echo "$diff" 
          if [ $(echo "$?") == 0 ];then
            echo "changed"
            sourceDiff=true
          else;
            echo "not changed"
          fi
          echo "docs_changed=$sourceDiff" >> $GITHUB_OUTPUT

  # Run the job only with "docs_changed" equals "True"
  conditional_job:
    runs-on: "ubuntu-20.04"
    needs: [conditional_job_check_files]
    if: needs.conditional_job_check_files.outputs.docs_changed == 'True'
    steps:
      - shell: pwsh
        run: echo publish docs
  first-job:
    needs: [conditional_job]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: downloading repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip3 install pytest
      - name: initating the testing
        run: |
          cd test
          pytest test_*.py
      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: ganesh.sonawane.9942@gmail.com,ganeshsonawane5896@gmail.com,ganesh.sonawane@interactiveavenues.com
          # from email name
          from: Ganesh Sonawane

          # diff=$(git diff --name-only HEAD^ HEAD)
          # echo "working"
          # sourceDiff=$(echo "$diff" | grep -E '^sampleaction/')
          # echo "working"
          # hasDiff=$sourceDiff.length -gt 0
          # echo "working"
          # if [ -n "$sourceDiff" ]; then
          #   hasDiff=true
          # fi
          # echo "working"
          # echo "docs_changed=$hasDiff" >> $GITHUB_OUTPUT

          # diff=$(git diff --name-only HEAD^ HEAD)
          # echo "working"
          # sourceDiff= $(echo "$diff" | grep '^sampleaction/')
          # echo "working"
          # hasDiff=$sourceDiff.length -gt 0
          # echo "working"
          # if [ -n "$sourceDiff" ]; then
          #   hasDiff=true
          # fi
          # echo "working"
          # echo "docs_changed=$hasDiff" >> $GITHUB_OUTPUT

          #      hasDiff=$sourceDiff.length -gt 0
          # echo "working"
          # if [ -n "$sourceDiff" ]; then
          #   hasDiff=true
          # fi

          # echo "here is correct $val"
          # if echo "$diff" | grep 'sampleaction/*'; then
          #   sourceDiff=true
          #   echo "inside diff"
          # else:
          #   sourceDiff=false
          #   echo "diff is false"
          # fi
          # echo "working"
          # hasDiff=false
          # if [ $sourceDiff==true ]; then
          #   hasDiff=$true
          #   echo "sourcediff true"
          # else:
          #   hasDiff= false
          # fi
          # echo "working2"
# echo "$diff" | grep "sampleaction/*"
